language: cpp
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
addons:
  apt:
    packages: lcov
  homebrew:
    packages: lcov
install:
  - pip install --user cpplint
before_scirpt: ./lint.sh
script: cd tests && ./test.sh
